### ISSUE TITLE
Animation Framework Overhaul

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#578]
Continuing from #567, it seems that there is a general consensus that the animation system needs an overhaul. 

Everyone seems to agree that the GL thread should be responsible for managing animation time steps. The exact means of doing this seems to be up in the air still so as @AndrewJo suggested, I am creating a new issue here to continue the discussion. 

---
## TODO
- [x] Rewrite base animation class.
- [x] Rewrite animation queue
- [x] Add and test new ColorAnimation3D
- [x] Adapt and test BezierPath3D
- [x] Adapt and test CatmullRomPath3D
- [x] Adapt and test RotateAnimation3D
- [x] EllipticalOrbitAnimation3D
- [x] ~~Adapt and test RotateAroundAnimation3D~~ (deprecated for EllipticalOrbitAnimation3D)
- [x] ~~Adapt and test RotationAnimation~~ (deprecated and consolidated into RotateAnimation3D)
- [x] Adapt and test ScaleAnimation
- [x] Adapt and test TranslateAnimation3D
- [x] Fully test all core animation functionality
- [x] Update RajawaliExamples to use new animation code.
- [x] Update Rajawali Wiki to use new animation code.
