### ISSUE TITLE
Anchor Stream and the next release

### ISSUE THREAD

**Issue by MasDennis** [Rajawali/Rajawali#887]
(this concerns @jwoolston , @ToxicBakery , @jayschwa , @Davhed , @AndrewJo )

The list of tasks for Anchor Steam seems to be growing instead of shrinking :)
So I was thinking to push some of the tasks to the next release.
Tasks related to API changes, scene graph and post processing should be in Anchor Steam and I think the rest (like renderscript, VBO interleaving, etc) should be pushed to the next release (1.1).

This way we can push out Anchor Steam and people can start using the new API.

So now the big question is: what will be the code name for the next release?
Maybe [Bintang](http://fc03.deviantart.net/fs71/i/2011/138/1/2/bintang_beer_by_thebulanoven-d3gm9s6.jpg), [Bali Hai](http://abjourney.com/wp-content/uploads/2012/02/DSC01140-e1329512342269.jpg), [Bitburger](http://www.pintprice.com/brands/Bitburger.jpg), [Brooklyn](http://www.jamesclay.co.uk/beer-suppliers/images/stories/product_pics/brooklyn.jpg) ... but suggestions are welcome :)

Thoughts?
## Included Issues Discussion
- [x] #829 I think we should resolve this issue, either by deciding to not generalize or doing it. Its a pretty small one.
- [x] #572 I see this as an API change and we have begun the process somewhat so lets finish it off
- [x] #798 This one is obvious. I (@jwoolston) am the big hold up here with the scene graph stuff...see below.
- ~~[ ] #535 I have been hit with a looming deadline at work. `RajawaliScene` is ready to go but the scenegraph stuff is not. If we are talking about in a few weeks, I likely can get the API stable (it pretty much is already) and the basic implimentation finished. If thats too long then I say we push `RajawaliScene` and leave the scenegraph out for the next. In this case we would execute #798 and I will deal with the difficulty on my end.~~
- [x] #794 This is small, I just want to make sure its not forgotten.
- [x] #750 This has been in progress for a while now but we should be sure its ready to go, including documentation.
