### ISSUE TITLE
Overhaul Quaternion and its uses

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#963]
In light of some recent issues, it has become clear that `Quaternion` needs some overhaul. Furthermore, the process has been started as seen below and this is related to `Vector3`. Some of these issues have impacted the development of the scene graph framework (#535) in both good and bad ways so I feel I should get this resolved. 

It is @ToxicBakery's suggestion to look at the libGDX version. This is an immutable type which I have some reservations about although it would fix a number of issues we have had with them. For reference their implimentation can be seen here:

https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/math/Quaternion.java
## Known Related Issues
- [x] #948 Provided a static lookAt method for `Quaternion`
- [x] #950 Reduced new object creation in `Quaternion` and `Vector3`
- [x] #957 `Quaternion` SLERP does not return normalized result
- [x] #961 Inconsistent normalization in `Quaternion`
- [x] #920 setLookAt() disables `Quaternion` based orientation
